# Generated by Django 2.1 on 2019-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
